version: "2.4"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  #db:
  #  build: ./infra/mysql
  #  volumes:
  #    - db-store:/var/lib/mysql

#volumes:
#  db-store:
