version: "2.4"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      # composer create-project laravel/laravel=8.0 sample
      # composer require nuwave/lighthouse
      # php artisan vendor:publish --tag=lighthouse-schema
      # composer require mll-lab/laravel-graphql-playground
      # mysqlへの接続
      # mysql -h 172.18.0.2 -P 3306 -u phper -p
  
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
